![Cultural Data Analysis · Week 1: Python](https://goto4711.github.io/cda-teaching-tools/assets/notebooks/week1-banner.png)

# Python Introduction Lecture

*Lecture notebook with solutions* · Code-along: [goto4711.github.io/cda-teaching-tools/code-along/week1](https://goto4711.github.io/cda-teaching-tools/code-along/week1/) · Tools: [CPU simulator](https://goto4711.github.io/cda-teaching-tools/tools/cpu/), [loops in four languages](https://goto4711.github.io/cda-teaching-tools/tools/loops/)

---

## Interacting with Environment

Welcome to your first session on how to use Python interactively in Jupyter notebooks.

> **Goals** · By the end of this session, you will be able to:
> - use Jupyter notebooks for basic calculations
> - understand fundamental Python data types
> - work with variables
> - use built-in functions
> - create and manipulate lists,
> - and understand basic control flow (if/else) and loops (for).

Let's just try to get used to interacting with the environment. Run the cell below by using 'run' in the menu or by clicking on the little grey arrow on the left. You can also use keyboard shortcuts: 'ctrl + enter to run current cell' (https://colab.research.google.com/drive/13IO3-gfyS9mSPuzAo6-wsYBUOVpxb_va?usp=sharing#scrollTo=bkyJsT1wCDbn).

In [91]:
# Keep cell
4

4

It is printing! The notebook displayed the number 4. This is because Jupyter notebooks will automatically display the result of the last unassigned expression in a code cell.

Let's try to add two numbers. Please, type ```2 + 1``` into cell below. Then, run the cell.

In [92]:
2 + 1

3

Now, let's try ```10 - 3```.

In [93]:
10 - 3

7

In the next cell try out further operations. Try multiplication with `3 * 7` and/or division with `10 / 2`.

In [94]:
10/2

5.0

And finally, brackets can be used to indicate that operators in the sub-expression take precedence - just like at school math. Try ```(1 * 2) - 100```.

In [95]:
(1*2) - 100

-98

These were all numbers. All this is very similar to what you know from calculators. But computers can process many other symbols as well. Other important symbols include 'strings', which you know as words. These can be any number of characters like 'a', 'b', 'c', etc. but also '-', '1' or '&' can be  characters.

Let's try this ...

Please, type ```'Amsterdam'``` into the Cell's prompt. The quotation marks indicate that this is a string. You could also use double quotation marks: ```"Amsterdam"```.

Normally, it does not matter much which version of quote you use, but it is useful if you have quotes within the string. Then, use the single quote for the whole string and the double quote for the quote. This is useful if your string itself contains one type of quote, e.g., 'He said "Hello!"'

In [96]:
'Amsterdam'

'Amsterdam'

What do you see when you enter ```type('Amsterdam')```?

In [97]:
type('Amsterdam')

str

str stands for strings.


---

## Data Types

There are many more types, which we will cover throughout the course. Check out: https://realpython.com/python-data-types/


We have already used so-called integers, which are basic numbers. Try ```type(333)```

In [98]:
type(333)

int

Numbers in Python are generally either integers (those without a floating point) or floats (those with a floating point). Check out https://docs.python.org/3/library/stdtypes.html for an overview of all the different numerical types in Python. It looks scary but in practice we only use two more types. The first are floating point numbers, which have a decimal point. Enter ```type(3.14)```.

In [99]:
type(3.14)

float

Booleans are the second important type we use regularly. They evaluate whether an assumption is True or False. Please, type ```10 < 8```. What do you get back?

In [100]:
10 < 8

False

The statement is false. This False value is a so-called Boolean. You can check its type with `type(10 < 8)`.

In [101]:
type(10 < 8)

bool

Other comparison operators include > (greater than), == (equal to), != (not equal to), >= (greater than or equal to), and <= (less than or equal to). Try a few by overwriting the last cell.

You can also add numbers of different types like in a calculator. Try ```333 + 3.14```.

In [102]:
333 + 3.14

336.14

What is the type of the result? Try `type(333 + 3.14)`. This demonstrates successful type conversion: (int + float -> float).

In [103]:
type(333 + 3.14)

float

> **⚠️ Expect an error** · A common error is the attempt to combine two data types that do not really go together without providing  more details. Try ```'three' + 3```.

You cannot add a string to an int. Seems logical, no?

Variables are another important concept that discriminates programming languages from calculators. They are basically names for places in the computer's memory where we can store things. We create variables with the Python assignment operator =.

Let's try that and assign the value 4 to the variable `my_friends`. Please, type in ```my_friends = 4``` for the number of friends I have.

In [104]:
my_friends = 4

> **💡 Remember** · Well done. Using descriptive names like `my_friends` instead of just `x` makes your code much easier to understand later. Always follow this principle. It is very good practice to use names that you can understand in 10 years when you look at your code again.

Now print out my_friends. Just type ```my_friends```.

In [105]:
my_friends

4

Now let's try to assign another variable for my number of colleagues.

Type ```my_colleagues = 3```.

In [106]:
my_colleagues = 3

You have now created two variables `my_friends` and `my_colleagues`.

Just like numbers we can add two numerical variables. Please try it with ```my_friends + my_colleagues```.

In [107]:
my_friends + my_colleagues

7

We can also assign the result to a new variable `my_friends_and_colleagues`. Please type ```my_friends_and_colleagues = my_friends + my_colleagues```.

In [108]:
my_friends_and_colleagues = my_friends + my_colleagues

> **💡 Remember** · I am using the _ to separate words in variable names. This is common good practice.

To check that the new variable exists, please enter ```my_friends_and_colleagues```.

In [109]:
my_friends_and_colleagues

7

But we can only combine variables of the same type. Please assign the string 'six' to my_colleagues with ```my_colleagues = 'six'```.

In [110]:
my_colleagues = 'six'

> **⚠️ Expect an error** · Now let's try and 'add' `my_friends` and `my_colleagues`. Type ```my_friends + my_colleagues``` and you will get an error.

Variables are very important in any programming language.

Another key idea is the function. It is  a predefined set of commands. On your calculator you can, for instance, use the inv-function to get the inverse of a number. Python also has a lot of pre-defined functions like inv. But in any programming language you can also define your own functions. We will come back to this later. For now, we stay with pre-defined functions.

In Python, functions are called with arguments in brackets. They are often found in extra libraries that are basically collections of functions. More on libraries also later ...

You have already used the type function to determine the type of numbers and strings. There are many, many more.

Please run ```round(3.78)``` to run the built-in math function round in Python. You should get 4. ```round``` is the function name and 3.78 is the only 'argument' as the input into functions is called.

In [111]:
round(3.78)

4

We can count the number of characters in a string with the function ```len```. Run ```len('Amsterdam')```.

In [112]:
len('Amsterdam')

9

Functions work with all data types as arguments. Let's try one more with ```abs(-10)```. What does this do?

In [113]:
abs(-10)

10

`abs` returns the absolute value of a number.

> **📖 Read more** · Check out https://docs.python.org/3/library/functions.html for a complete overview of all built-in functions. Play with a few more ... Some might be hard to understand at this time.

One important function that we have not talked about is ```print```. It simply prints out a statement. Try ```print('Amsterdam')```.

In [114]:
print('Amsterdam')

Amsterdam


Jupyter notebooks automatically print the result of the last expression in a code cell if it's not assigned to a variable. This contrasts with using the `print()` function, which is more explicit and can print multiple things.


You can print integers, too. Enter ```print(5)```.

In [115]:
print(5)

5


As you can see at https://realpython.com/python-print/, `print` is very powerful and has a lot of options to format the output. For instance, if you type in ```print('Hello', 'Amsterdam', sep='_')```, you print out Hello_Amsterdam. The strings are concatenated using the sep argument, which is '_'.

In [116]:
print('Hello', 'Amsterdam', sep='_')

Hello_Amsterdam


With '\n', you indicate a line break. What happens if you type in ```print('Hello', 'Amsterdam', sep='\n')```. Try it.

In [117]:
print('Hello', 'Amsterdam', sep='\n')

Hello
Amsterdam


There are many advanced formatting options for print, which we will cover in the course.

Next to numbers, strings are very important in Python and other languages. They come with many functions as well. Check out: https://docs.python.org/3/library/string.html. We have already seen ```len``` and will cover many more string functions in this course. One important one is concatenation outside ```print```. In Python, the ```+``` operator is used again. Try ```'Hello' + ' Amsterdam'```.   

In [118]:
'Hello' + ' Amsterdam'

'Hello Amsterdam'

You can also concatenate several strings. Type in ```'Hello' + ' ' + 'Amsterdam'```.

In [119]:
'Hello' + ' ' + 'Amsterdam'

'Hello Amsterdam'

There is a more recent development in Python called f-strings as a modern way to format strings, especially if these are mixing text and variables. Run the next cell and try to understand.

In [120]:
#Keep cell

name = 'Me'
age = 20

print(f"Hello, {name}! You are {age} years old.")

Hello, Me! You are 20 years old.


As you can see in the `print` statement, the `f` before the string makes it easy to integrate variables with the `{}` brackets.

f-strings have gained a lot of traction in recent years with the work on chatbots, as we will see in later sessions. Here, we focus on other more introductory concepts and move on to combining data in lists and arrays.



---

## Lists and Arrays


With so-called lists, you can collect several elements in the same variable. This is immensely useful for collecting data. You will see a lot of use of data collections in this course.

Let's try to make lists, which store an ordered set of values called elements. A list can contain any number of elements using brackets. They are ordered, mutable (can be changed) and can hold items of different types.

Type in `numeric_list = [3, 9, 27]` to create a numeric list of three numbers.

In [121]:
numeric_list = [3, 9, 27]

To check that the new list exists, please type ```numeric_list```.

In [122]:
numeric_list

[3, 9, 27]

We can also create a string/characters list, with ```string_list = ['abc', 'def', 'ghi']```.

In [123]:
string_list = ['abc', 'def', 'ghi']

To check that the new list exists, please type ```string_list```.

In [124]:
string_list

['abc', 'def', 'ghi']

Lists are useful to, for instance, keep a record of the friends you meet during the week. You do not see friends on Saturday and Sunday, as you stay home with family, but you record all the other 5 days. You enter ```friends_list = [2, 3, 2, 4, 5]```.

In [125]:
friends_list = [2, 3, 2, 4, 5]

You feel very communicative this week. So, you also meet up with colleagues. Please record your meetings with ```colleagues_list =[3, 1, 1, 10, 2]```.

In [126]:
colleagues_list = [3, 1, 1, 10, 2]

Because you prefer it organised, you would now like to name each of the entries. Such 'named lists' are possible in Python with dictionaries. Please create an empty dictionary by typing ```names_friends = {}```.

In [127]:
names_friends = {}

To create a dictionary (which is like a named list), simply use the {} and then for each element the key to access the element comes first, then a ':', and finish it with the value.

So, in order to create a dictionary containing all your friends, type in ```names_friends = {'Monday': 2, 'Tuesday': 3, 'Wednesday': 2, 'Thursday': 4, 'Friday': 5}```.

Dictionaries are further explained at https://www.w3schools.com/python/python_dictionaries.asp.

In [128]:
names_friends = {'Monday': 2, 'Tuesday': 3, 'Wednesday': 2, 'Thursday': 4, 'Friday': 5}

Let's take a look at the type with `type(names_friends)`. Type it in.

In [129]:
type(names_friends)

dict

Python dictionaries use curly braces `{}` with key-value pairs: `key: value`, separated by commas. Keys must be unique.

Now you can access a single element with ```names_friends['Monday']```.

In [130]:
names_friends['Monday']

2

This was just an introduction to dictionaries. We will come back to them many times throughout this course.

Next, you are interested in how many people you meet per week.

You can simply add up all the elements in the list. Remember that we can use built-in functions?

To add up elements in a list we can use the function sum, which comes directly with Python. Try it with ```sum(friends_list)```.

In [131]:
sum(friends_list)

16

And of course we can also do ```sum(colleagues_list)```.

In [132]:
sum(colleagues_list)

17

In order to get our total meetings for the week, we can simply add both lists with the Python `sum` function. Type in ```total_week = sum(friends_list) + sum(colleagues_list)```.

In [133]:
total_week = sum(friends_list) + sum(colleagues_list)

Print out `total_week`.

In [134]:
total_week

33

We have almost covered everything there is to know about lists. One more important concept is that lists are indexed. Using square brackets, we can select the first, second and third element directly with 0, 1, 2, etc. respectively. So, the index count in Python starts with 0 for the first element. The index of the last element is then the length of the list n – 1.

To select Monday's friends (first day of the week) simply use square brackets [] and type ```friends_monday = friends_list[0]```.

In [135]:
friends_monday = friends_list[0]

Print out `friends_monday`.

In [136]:
friends_monday

2

You can also select more than one element with the colon `:` operator.

In order to select your meetings with colleagues from Tuesday to Thursday, please run ```colleagues_selection_list = colleagues_list[1:4]```.  The first value, left of the colon, is the first index to select (in this case Tuesday). The last value is the first index NOT to select (here Friday). Watch out, as it can be confusing.

Print out colleagues_selection_list in the same cell. You do this by entering each command in one line:
```
colleagues_selection_list = colleagues_list[1:4]
colleagues_selection_list
```

In [137]:
colleagues_selection_list = colleagues_list[1:4]
colleagues_selection_list

[1, 1, 10]

This is called list slicing in Python and requires some getting used to. It is, however, a key element of Python for working with datasets.

If you have a list l, these are the options:

- l[start:stop]  # items start through stop-1
- l[start:]      # items start through the rest of the array
- l[:stop]       # items from the beginning through stop-1
- l[:]           # a copy of the whole array


You can also use negative indices. `friends_list[-1]` gives you the last element, `friends_list[-2]` the second to last, and so on. Try getting the last element of `friends_list`.

In [138]:
friends_list[-1]

5

To find out the total number of colleagues' meetings from Tuesday to Thursday, we can use `sum` again. Try ```sum(colleagues_selection_list)```.

In [139]:
sum(colleagues_selection_list)

12

Using the index we can also update elements in lists.

Let's set the Wednesday meetings of colleagues_selection_list to 1000 with ```colleagues_selection_list[1] = 1000```.

In [140]:
colleagues_selection_list[1] = 1000

Print out `colleagues_selection_list` and the sum of the list in the same cell. You need to use `print()` for both statements, as otherwise you will only print out the last statement.

In [141]:
print(colleagues_selection_list)
print(sum(colleagues_selection_list))

[1, 1000, 10]
1011


We can change lists by appending items at the end. This is done with the ```append``` function. Try to run ```colleagues_selection_list.append('10')```. You have updated the list with a new item at the end. Print `colleagues_selection_list` in the same cell.

In [142]:
colleagues_selection_list.append('10')
colleagues_selection_list

[1, 1000, 10, '10']

Run the cell a couple of times. Each time a new '10' will be appended. Also, note that '10' is a string. Lists can contain different data types.

With ```remove```, you will remove the items again. Try ```colleagues_selection_list.remove('10')```. Print out the list.

In [143]:
colleagues_selection_list.remove('10')
colleagues_selection_list

[1, 1000, 10]

Please note, `remove()` will only remove the first occurrence of the item. If the item is not found, Python will raise a `ValueError`.

It's time to practice some more at https://www.w3schools.com/python/python_lists.asp.

Two more items common in data analysis are sets and tuples. Both are closely related to lists, and we only mention their common use cases.

Sets are a construct you already know from school and means a list without duplicates. Type in `set(friends_list)` and compare the results with ```friends_list```.

In [144]:
set(friends_list)

{2, 3, 4, 5}

You have just eliminated duplicates from ```friends_list```.

Tuples are used to store multiple items in a single variable. They are unchangeable. We cannot change, add or remove items after the tuple has been created.

The example at https://www.w3schools.com/python/python_tuples.asp is ```my_tuple = ('apple', 'banana', 'cherry')```. Type it in and print it out.

In [145]:
my_tuple = ('apple', 'banana', 'cherry')
my_tuple

('apple', 'banana', 'cherry')

> **⚠️ Expect an error** · Try ```my_tuple[0] = 'kiwi'``` and you will get an error. Tuples are immutable.

> **💡 Remember** · Tuples might look a bit strange, but they will be useful later, when we create and modify more complex datasets. For now, just remember that *lists are using `[]`, dictionaries `{}` and tuples `()`*.

The next new concept is the NumPy array. You often use this construct in data analysis.

NumPy has been a long-standing toolkit for data analysis. According to https://numpy.org/, it is 'the fundamental package for scientific computing with Python'. It features heavily in what is still a standard introduction in our field: https://wesmckinney.com/book/. It is a really good book to further work on the topics that are discussed in these introductions.

First, we have to import the NumPy package. This simply means that we import all the functionalities and data that are associated with the package. You always do that in Python with import. In this case, type in ```import numpy```.

In [146]:
import numpy

A Python package is a container with various functions to perform specific tasks. For example, the math package includes the `sqrt()` function to perform the square root of a number. Run
```
import math
math.sqrt(9)
```

In [147]:
import math
math.sqrt(9)

3.0

We will use a lot of packages and import other functions. This is all part of building complex programmes around the principles of abstraction and modularity: https://courses.csail.mit.edu/6.01/spring07/psets/lecture1.pdf. In the future, you can also contribute by providing your own packages.

If you use a package very often and you are too lazy to type in the full name each time, you can also create a short version.

To call `numpy` `np`, try ```import numpy as np```.

In [148]:
import numpy as np

Now you can create a NumPy array with ```np.array([1,2,3,4])```. As you can see, you provide `np.array` with a Python list. Why do we then not use a simple list, you may ask? Arrays are much more powerful, as we will see.

In [149]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

NumPy arrays are designed for efficient numerical operations, especially on large datasets. They typically store elements of the same data type, unlike Python lists. And, they are very important for machine learning, as we will see from week 3 onwards.

We will now recreate our social life examples using NumPy arrays.

Type in ```friends_array = np.array([5,4,2,5,3])``` to record the number of times you have met with friends.

In [150]:
friends_array = np.array([5,4,2,5,3])

Now, create ```colleagues_array = np.array([1,10,8,1,5])```.

In [151]:
colleagues_array = np.array([1,10,8,1,5])

Print out `colleagues_array` to see that it is a NumPy array.

In [152]:
colleagues_array

array([ 1, 10,  8,  1,  5])

Functions of NumPy that you will use a lot are simple statistics like the mean or median. If you don't remember what these all are, read up and play at https://www.w3schools.com/python/python_ml_mean_median_mode.asp.

You can calculate the mean of friends' visits with ```np.mean(friends_array)```.

In [153]:
np.mean(friends_array)

np.float64(3.8)

For the median, try ```np.median(friends_array)```.

In [154]:
np.median(friends_array)

np.float64(4.0)

The mean value is the average value. The median value is the value in the middle, after you have sorted all the values. If they are close together, the values are fairly evenly distributed. We talk about this more next week.

Matrices are important in data analysis. They are two-dimensional arrays. For instance, black and white images are such matrices. They contain a pixel value at the horizontal and vertical dimension.

We can create a matrix called meetings by simply combining `friends_array` and `colleagues_array`. Type in ```meetings = np.array([friends_array, colleagues_array])```. Print out `meetings`.

In [155]:
meetings = np.array([friends_array, colleagues_array])
meetings

array([[ 5,  4,  2,  5,  3],
       [ 1, 10,  8,  1,  5]])

Type in `meetings.shape` and analyse the output.

In [156]:
meetings.shape

(2, 5)

The attribute `shape` gives you the dimensions of an array.

We can then ask a couple of good questions against the matrix `meetings` without having to reference the arrays it is made of.

To find out on which days we had 5 meetings with either friends or colleagues, we type ```meetings == 5```. The == is the Boolean equivalence operator.

In [157]:
meetings == 5

array([[ True, False, False,  True, False],
       [False, False, False, False,  True]])

Want to see something nice? It is very easy to find out the number of times meetings == 5 with `np.sum(meetings == 5)`.

In [158]:
np.sum(meetings == 5)

np.int64(3)

This is very advanced and something you will learn over time, but all Boolean values are at the same time 0 or 1 for False or True. With `np.sum`, we simply sum up the number of times we have True (which equals 1) in meetings.

When are the meetings less than or equal to 7? Try ```meetings <= 7```.

In [159]:
meetings <= 7

array([[ True,  True,  True,  True,  True],
       [ True, False, False,  True,  True]])

How often do I meet friends equal or more than colleagues times two? This is actually a quite advanced expression already. Try it with ```np.sum(friends_array >= (colleagues_array * 2))```.

In [160]:
np.sum(friends_array >= (colleagues_array * 2))

np.int64(2)

Take a moment to think about the components of this expression. Maybe, you want to take a piece of paper and pen to write down all the components. Hint: As said, Boolean variables can also be thought of as 0 for False and 1 for True.

Similar to arrays, we can access each element of a matrix, but this time we have 2 dimensions. ``meetings[0][2]`` will select the first row's third element. Try it.

In [161]:
meetings[0][2]

np.int64(2)

The order of indexes is row first and then column. Enter `meetings[1][2]`.

In [162]:
meetings[1][2]

np.int64(8)

> **⚠️ Expect an error** · Be very careful with indexes. If you go beyond the number of elements in lists or arrays you produce an error. Try ```meetings[2][2]```.

It is called 'index out of bounds' and is a very common error in programming.

This is very important for image-processing, as we will see later on. Images in Python are treated as matrices because they consist of pixels arranged in a grid—rows and columns. Think of your screen in front of you.

It's time to practice and read up a bit at https://numpy.org/doc/stable/user/absolute_beginners.html.

We are almost done for today. Finally, we want to look at what are called control structures for events and loops. They are both very powerful.

---

## Event-driven and Sequential

In this week's workshop, we will go again over all the concepts and practices we have just discussed.  But before that, we need to introduce a few more aspects of Python, the programming language, which you might need in data analysis tasks, but they are much more common if you want to program say an app. The first topic is control structures.

Control structures execute a piece of code based on a condition. You can recognise them in most programming languages by the keyword `if`. In Python, they look like the cell below. Run the next cell, please.

In [163]:
#Keep cell
medium = 'Social Media'

if (medium == 'Social Media'):
    print('Showing Social Media information')

Showing Social Media information


The first statement creates a variable `medium` with 'Social Media' as a value. The control structure starts with `if`, then uses a condition to evaluate to a Boolean (`medium == 'Social Media'`), followed by a colon. The statement to execute follows in the next line.  `print('Showing Social Media information')` will print out if the condition is met.

Important: Observe the indentation, which is a way of telling Python that a group of statements belongs together as a block. Blocks can be regarded as the grouping of statements for a specific purpose. Python really does not like if you mess with its indentation. Check https://www.dummies.com/article/technology/programming-web-design/python/how-to-indent-and-dedent-your-python-code-139545/.

Now, also assign ```num_views = 1001```.

In [164]:
num_views = 1001

Let's try to confirm whether we are popular with ```if num_views > 1000``` then print 'You are very popular!'

Now, using the `num_views` variable, write an if statement that prints 'You are very popular!' if `num_views` is greater than 1000. You can do it ...

In [165]:
if (num_views > 1000):
    print('You are very popular!')

You are very popular!


You can combine Boolean expressions/conditions also logically.


The keyword 'and' stands for a logical and, while 'or' stands for the logical or in Python.

Try the logical combination and and type in:

```
if (num_views > 1000) and (medium == 'Social Media'):
    print('You are popular on Social Media!')
```

Explain the results!

In [166]:
if (num_views > 1000) and (medium == 'Social Media'):
    print('You are popular on Social Media!')

You are popular on Social Media!


`num_views > 1000` and `medium == 'Social Media'` means that the if condition is met and 'You are popular on Social Media!' is printed.

Finally, you can also tell the computer to do other work if the condition is not fulfilled. You need to use the keyword `else`. Run the cell below and observe the indentation ...

In [167]:
#Keep cell

if (num_views > 1000) and (medium == 'Social Media'):
    print('Condition met.')
    print('You are popular on Social Media!')
else:
    print('Condition not met.')
    print('Try to be more visible!')

Condition met.
You are popular on Social Media!


> **📖 Read more** · W3Schools is a great free site with lots of exercises on various aspects of the Python programming language. Go to https://www.w3schools.com/python/python_conditions.asp and complete all the exercises before you continue. As you can see there are other topics, too, like variables: https://www.w3schools.com/python/python_variables.asp. We will come back to the site from time to time to keep practicing.

These are control statements. Let's move on to sequences and loops.

Loops can be used to iterate over the elements of lists and arrays. Let's look at our friends again. Print out ```friends_list``` and ```friends_array```. You need to use the print statement and ```,``` to print them out both at the same time. Do you remember how?

In [168]:
print(friends_list, friends_array)

[2, 3, 2, 4, 5] [5 4 2 5 3]


Can you achieve the same result with an f-string? Try it ...

In our Python world of data analysis, for loops are especially important. They are used to iterate over a sequence (like a sequence of letters in a string here). The cell below shows the syntax. Run it.

In [169]:
#Keep cell

for letter in 'LinkedIn':
    print(letter)

L
i
n
k
e
d
I
n


For loops can be very useful to perform repeated operations on collections of data, which is something we often want to do in data analysis. So, for instance, loops could be used to get the square of each element in a list/array, etc.

The next cell introduces the ```for i in``` construct, which is a short form for going through elements in a for loop. Run the following code to square each number in our ```range(9)``` and observe the code:

```
for i in range(9):
    print(i**2)

```

```i**2``` is the power-operator in Python.

In [170]:
for i in range(9):
    print(i**2)

0
1
4
9
16
25
36
49
64


This was a lot of stuff for the first lesson. Unfortunately, this is necessary but once you have learned one programming language all of this becomes quite obvious and repetitive.

Now, we are ready to use loops for what we generally use them for and access each element in a list or array. Please create a for loop to iterate over `friends_list`. It is very easy in Python but watch out for those indentations.

```
for f in friends_list:
  print(f)
```

In [171]:
for f in friends_list:
  print(f)

2
3
2
4
5


The for loop starts with a `for`, then the variable to iterate with, then the `in`, plus finally the list followed by a colon.

You can do the same with the array. Try:

```
for f in friends_array:
  print(f)
```

In [172]:
for f in friends_array:
  print(f)

5
4
2
5
3


In [173]:
friends_array

array([5, 4, 2, 5, 3])

You can also use an index that runs from 0 to 4 in these two cases. Remember the function ```range``` from earlier? It was easy to miss. Try ```list(range(5))``` and observe how it creates a list from 0 to 4.

In [174]:
list(range(5))

[0, 1, 2, 3, 4]

So, to use an index i to iterate over friends_list, enter
```
for i in list(range(5)):
  print(friends_list[i])
```

In [175]:
for i in list(range(5)):
  print(friends_list[i])

2
3
2
4
5


Now, we can update each element in the list. To double the values, run:

```
for i in list(range(5)):
  friends_list[i] = friends_list[i] * 2
```

In [176]:
for i in list(range(5)):
  friends_list[i] = friends_list[i] * 2

Print out `friends_list` and compare.

In [177]:
friends_list

[4, 6, 4, 8, 10]

This is where arrays are much easier. Here you do not have to use a for-loop. Run ```friends_array = friends_array * 2``` and be amazed.

In [178]:
friends_array = friends_array * 2

This updates the elements of friends_array directly. Print `friends_array`.

In [179]:
friends_array

array([10,  8,  4, 10,  6])

Let's bring loops and conditions together and compare `friends_list` and `friends_array`.

We want to print out 'The lists have it!' each time the `friends_list` element at position `i` is larger than or equal to the `friends_array` element at position `i`. Otherwise, we print 'The arrays have it!'.

Take a moment to think how to do it. You need both for-loops and if-statements.

After some thinking, you type:

```
for i in list(range(5)):
    if (friends_list[i]>=friends_array[i]):
        print('The lists have it!')
    else:
        print('The arrays have it!')
```

In [180]:
for i in list(range(5)):
    if (friends_list[i]>=friends_array[i]):
        print('The lists have it!')
    else:
        print('The arrays have it!')

The arrays have it!
The arrays have it!
The lists have it!
The arrays have it!
The lists have it!


> **📖 Read more** · Have even more fun with for-loops at https://www.w3schools.com/python/python_for_loops.asp.

Looking forward to seeing you again at the workshops.